# Generated by Django 4.0.4 on 2022-05-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_bikeimage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('db_biketitle', models.CharField(max_length=100)),
                ('db_bikeprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('db_bikeinfo', models.CharField(max_length=100)),
                ('db_bikecategory', models.CharField(max_length=100)),
            ],
        ),
    ]
